name: Export Cache
on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      # 加载你原有的环境变量（必须）
      - name: 加载全局变量
        run: grep -v '^#' Part0_Global.env | grep -v '^$' >> $GITHUB_ENV

      # 创建目录 + 赋权限（和你原流程完全一样）
      - name: 创建缓存目录
        run: |
          sudo mkdir -p ${{ env.CACHE_SYNC }}
          sudo chown $USER:$GROUPS ${{ env.CACHE_SYNC }}

      # 👇 这一步就是你原流程里的【恢复缓存】，100% 能成功
      - name: 恢复编译缓存
        uses: actions/cache/restore@v5
        with:
          path: ${{ env.CACHE_SYNC }}
          key: Linux-sync-nanopc_t6-25964126010  # 你要提取的缓存KEY
          restore-keys: |
            Linux-sync-nanopc_t6-

      # 👇 恢复成功后，直接压缩上传，就能下载
      - name: 打包缓存并上传
        uses: actions/upload-artifact@v6
        with:
          name: openwrt-cache-complete
          path: ${{ env.CACHE_SYNC }}
          retention-days: 30
