name: Download Cache to Artifact
on:
  workflow_dispatch: # 手动触发，随时可以跑

jobs:
  restore-and-download:
    runs-on: ubuntu-latest
    steps:
      - name: Restore the target cache
        uses: actions/cache/restore@v4
        with:
          # 这里填你截图里的缓存key
          key: Linux-sync-nanopc_t6-25964126010
          # 这里用你图里给的路径
          path: /workdir/chenos

      - name: Upload cache as downloadable artifact
        uses: actions/upload-artifact@v6
        with:
          name: chenos-cache-backup
          path: /workdir/chenos
          retention-days: 30 # 保留30天，方便你下载
