#
# 文件路径：.github/workflows/Update.yml
# 文件说明：自动更新固件
#
# Copyright (c) 2026 ChenOSWrt
#

# 工作流Workflows名称
name: Update

on:
  # 允许手动点击运行
  workflow_dispatch:  
  # 定时自动检测（每18小时检查一次，目前被注释，未开启）
  #schedule:                 
  #  - cron: 0 */18 * * *

# 权限配置
permissions:
  contents: write
  packages: write

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:

    - name: 加载全局变量
      run: grep -v '^#' Part0_Global.env | grep -v '^$' >> $GITHUB_ENV   

    - name: 获取源码最新提交哈希
      id: get_hash
      run: |
        # 浅克隆源码：仅拉取最新1次提交，大幅减少拉取时间和磁盘占用
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH .
        # 取最新提交的唯一标识（Commit Hash）并输出到步骤输出
        echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: 对比缓存中的提交哈希
      id: cache_hash
      uses: actions/cache@v5
      with:
        path: .commitHash
        key: commitHash_${{ steps.get_hash.outputs.commitHash }}

    - name: 保存新提交哈希到缓存
      if: steps.cache_hash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.get_hash.outputs.commitHash }} | tee .commitHash

    - name: 触发Build工作流编译固件
      if: steps.cache_hash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v4
      with:
        token: ${{ github.token }}
        event-type: Source Code Update  # 触发事件：源码已更新（通知编译脚本开始工作）

    - name: 清理旧的Workflows运行记录
      if: always()
      run: |
        # 保留最新3条运行记录
        gh run list --workflow "${{ github.workflow }}" --limit all \
          --json databaseId -q '.[3:][] | .databaseId' \
          | while read -r id; do
              if [ -n "$id" ]; then
                echo "⚠️ 正在删除运行记录：$id"
                gh run delete "$id" || echo "❌ 删除失败：$id"
              fi
            done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
